version: '3'
services:
  postgres:
    build: .
    container_name: postgres-11
    ports:
      - "5434:5432"
    volumes:
      - "/volume1/Databases/postgresql-11/data:/var/lib/postgresql/data"
      - "/var/services/homes/developer/sql:/home/yukio/sql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
